// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.7.0
//
// <auto-generated>
//
// Generated from file `MP3IceInterface.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package mp3;

public class FileInfo extends com.zeroc.Ice.Value
{
    public FileInfo()
    {
        this.name = "";
        this.path = "";
        this.author = "";
        this.album = "";
        this.genre = "";
        this.year = "";
    }

    public FileInfo(String name, String path, String author, String album, String genre, String year)
    {
        this.name = name;
        this.path = path;
        this.author = author;
        this.album = album;
        this.genre = genre;
        this.year = year;
    }

    public String name;

    public String path;

    public String author;

    public String album;

    public String genre;

    public String year;

    public FileInfo clone()
    {
        return (FileInfo)super.clone();
    }

    public static String ice_staticId()
    {
        return "::mp3::FileInfo";
    }

    @Override
    public String ice_id()
    {
        return ice_staticId();
    }

    public static final long serialVersionUID = 839468939L;

    @Override
    protected void _iceWriteImpl(com.zeroc.Ice.OutputStream ostr_)
    {
        ostr_.startSlice(ice_staticId(), -1, true);
        ostr_.writeString(name);
        ostr_.writeString(path);
        ostr_.writeString(author);
        ostr_.writeString(album);
        ostr_.writeString(genre);
        ostr_.writeString(year);
        ostr_.endSlice();
    }

    @Override
    protected void _iceReadImpl(com.zeroc.Ice.InputStream istr_)
    {
        istr_.startSlice();
        name = istr_.readString();
        path = istr_.readString();
        author = istr_.readString();
        album = istr_.readString();
        genre = istr_.readString();
        year = istr_.readString();
        istr_.endSlice();
    }
}
