// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.7.0
//
// <auto-generated>
//
// Generated from file `MP3IceInterface.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package mp3;

public interface ManageMusic extends com.zeroc.Ice.Object
{
    String[] getListeMusic(com.zeroc.Ice.Current current);

    boolean streamerMusique(String mediaName, String ipClient, com.zeroc.Ice.Current current);

    boolean stopMusique(String ipClient, com.zeroc.Ice.Current current);

    String addFile(FileInfo fileInfo, com.zeroc.Ice.Current current);

    FileInfo[] afficherListeMusic(com.zeroc.Ice.Current current);

    String deleteMusic(FileInfo fileInfo, com.zeroc.Ice.Current current);

    FileInfo[] searchByAuthor(String author, com.zeroc.Ice.Current current);

    FileInfo[] searchByName(String name, com.zeroc.Ice.Current current);

    FileInfo[] searchByGenre(String genre, com.zeroc.Ice.Current current);

    FileInfo[] searchByYear(String year, com.zeroc.Ice.Current current);

    static final String[] _iceIds =
    {
        "::Ice::Object",
        "::mp3::ManageMusic"
    };

    @Override
    default String[] ice_ids(com.zeroc.Ice.Current current)
    {
        return _iceIds;
    }

    @Override
    default String ice_id(com.zeroc.Ice.Current current)
    {
        return ice_staticId();
    }

    static String ice_staticId()
    {
        return "::mp3::ManageMusic";
    }

    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_getListeMusic(ManageMusic obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        inS.readEmptyParams();
        String[] ret = obj.getListeMusic(current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        ostr.writeStringSeq(ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_streamerMusique(ManageMusic obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_mediaName;
        String iceP_ipClient;
        iceP_mediaName = istr.readString();
        iceP_ipClient = istr.readString();
        inS.endReadParams();
        boolean ret = obj.streamerMusique(iceP_mediaName, iceP_ipClient, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        ostr.writeBool(ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_stopMusique(ManageMusic obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_ipClient;
        iceP_ipClient = istr.readString();
        inS.endReadParams();
        boolean ret = obj.stopMusique(iceP_ipClient, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        ostr.writeBool(ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_addFile(ManageMusic obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        final com.zeroc.IceInternal.Holder<FileInfo> icePP_fileInfo = new com.zeroc.IceInternal.Holder<>();
        istr.readValue(v -> icePP_fileInfo.value = v, FileInfo.class);
        istr.readPendingValues();
        inS.endReadParams();
        FileInfo iceP_fileInfo = icePP_fileInfo.value;
        String ret = obj.addFile(iceP_fileInfo, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        ostr.writeString(ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_afficherListeMusic(ManageMusic obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        inS.readEmptyParams();
        FileInfo[] ret = obj.afficherListeMusic(current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        fileInfosHelper.write(ostr, ret);
        ostr.writePendingValues();
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_deleteMusic(ManageMusic obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        final com.zeroc.IceInternal.Holder<FileInfo> icePP_fileInfo = new com.zeroc.IceInternal.Holder<>();
        istr.readValue(v -> icePP_fileInfo.value = v, FileInfo.class);
        istr.readPendingValues();
        inS.endReadParams();
        FileInfo iceP_fileInfo = icePP_fileInfo.value;
        String ret = obj.deleteMusic(iceP_fileInfo, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        ostr.writeString(ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_searchByAuthor(ManageMusic obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_author;
        iceP_author = istr.readString();
        inS.endReadParams();
        FileInfo[] ret = obj.searchByAuthor(iceP_author, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        fileInfosHelper.write(ostr, ret);
        ostr.writePendingValues();
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_searchByName(ManageMusic obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_name;
        iceP_name = istr.readString();
        inS.endReadParams();
        FileInfo[] ret = obj.searchByName(iceP_name, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        fileInfosHelper.write(ostr, ret);
        ostr.writePendingValues();
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_searchByGenre(ManageMusic obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_genre;
        iceP_genre = istr.readString();
        inS.endReadParams();
        FileInfo[] ret = obj.searchByGenre(iceP_genre, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        fileInfosHelper.write(ostr, ret);
        ostr.writePendingValues();
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_searchByYear(ManageMusic obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_year;
        iceP_year = istr.readString();
        inS.endReadParams();
        FileInfo[] ret = obj.searchByYear(iceP_year, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        fileInfosHelper.write(ostr, ret);
        ostr.writePendingValues();
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    final static String[] _iceOps =
    {
        "addFile",
        "afficherListeMusic",
        "deleteMusic",
        "getListeMusic",
        "ice_id",
        "ice_ids",
        "ice_isA",
        "ice_ping",
        "searchByAuthor",
        "searchByGenre",
        "searchByName",
        "searchByYear",
        "stopMusique",
        "streamerMusique"
    };

    @Override
    default java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceDispatch(com.zeroc.IceInternal.Incoming in, com.zeroc.Ice.Current current)
        throws com.zeroc.Ice.UserException
    {
        int pos = java.util.Arrays.binarySearch(_iceOps, current.operation);
        if(pos < 0)
        {
            throw new com.zeroc.Ice.OperationNotExistException(current.id, current.facet, current.operation);
        }

        switch(pos)
        {
            case 0:
            {
                return _iceD_addFile(this, in, current);
            }
            case 1:
            {
                return _iceD_afficherListeMusic(this, in, current);
            }
            case 2:
            {
                return _iceD_deleteMusic(this, in, current);
            }
            case 3:
            {
                return _iceD_getListeMusic(this, in, current);
            }
            case 4:
            {
                return com.zeroc.Ice.Object._iceD_ice_id(this, in, current);
            }
            case 5:
            {
                return com.zeroc.Ice.Object._iceD_ice_ids(this, in, current);
            }
            case 6:
            {
                return com.zeroc.Ice.Object._iceD_ice_isA(this, in, current);
            }
            case 7:
            {
                return com.zeroc.Ice.Object._iceD_ice_ping(this, in, current);
            }
            case 8:
            {
                return _iceD_searchByAuthor(this, in, current);
            }
            case 9:
            {
                return _iceD_searchByGenre(this, in, current);
            }
            case 10:
            {
                return _iceD_searchByName(this, in, current);
            }
            case 11:
            {
                return _iceD_searchByYear(this, in, current);
            }
            case 12:
            {
                return _iceD_stopMusique(this, in, current);
            }
            case 13:
            {
                return _iceD_streamerMusique(this, in, current);
            }
        }

        assert(false);
        throw new com.zeroc.Ice.OperationNotExistException(current.id, current.facet, current.operation);
    }
}
