// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.7.0
//
// <auto-generated>
//
// Generated from file `MP3IceInterface.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package MP3;

public interface ManageMusicPrx extends com.zeroc.Ice.ObjectPrx
{
    default String addFile(fileInfo fileInfo)
    {
        return addFile(fileInfo, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default String addFile(fileInfo fileInfo, java.util.Map<String, String> context)
    {
        return _iceI_addFileAsync(fileInfo, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<java.lang.String> addFileAsync(fileInfo fileInfo)
    {
        return _iceI_addFileAsync(fileInfo, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<java.lang.String> addFileAsync(fileInfo fileInfo, java.util.Map<String, String> context)
    {
        return _iceI_addFileAsync(fileInfo, context, false);
    }

    default com.zeroc.IceInternal.OutgoingAsync<java.lang.String> _iceI_addFileAsync(fileInfo iceP_fileInfo, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.lang.String> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "addFile", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeValue(iceP_fileInfo);
                     ostr.writePendingValues();
                 }, istr -> {
                     String ret;
                     ret = istr.readString();
                     return ret;
                 });
        return f;
    }

    default fileInfo[] afficherListeMusic()
    {
        return afficherListeMusic(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default fileInfo[] afficherListeMusic(java.util.Map<String, String> context)
    {
        return _iceI_afficherListeMusicAsync(context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<fileInfo[]> afficherListeMusicAsync()
    {
        return _iceI_afficherListeMusicAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<fileInfo[]> afficherListeMusicAsync(java.util.Map<String, String> context)
    {
        return _iceI_afficherListeMusicAsync(context, false);
    }

    default com.zeroc.IceInternal.OutgoingAsync<fileInfo[]> _iceI_afficherListeMusicAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<fileInfo[]> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "afficherListeMusic", null, sync, null);
        f.invoke(true, context, null, null, istr -> {
                     fileInfo[] ret;
                     ret = fileInfosHelper.read(istr);
                     istr.readPendingValues();
                     return ret;
                 });
        return f;
    }

    default String deleteMusic(fileInfo fileInfo)
    {
        return deleteMusic(fileInfo, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default String deleteMusic(fileInfo fileInfo, java.util.Map<String, String> context)
    {
        return _iceI_deleteMusicAsync(fileInfo, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<java.lang.String> deleteMusicAsync(fileInfo fileInfo)
    {
        return _iceI_deleteMusicAsync(fileInfo, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<java.lang.String> deleteMusicAsync(fileInfo fileInfo, java.util.Map<String, String> context)
    {
        return _iceI_deleteMusicAsync(fileInfo, context, false);
    }

    default com.zeroc.IceInternal.OutgoingAsync<java.lang.String> _iceI_deleteMusicAsync(fileInfo iceP_fileInfo, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.lang.String> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "deleteMusic", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeValue(iceP_fileInfo);
                     ostr.writePendingValues();
                 }, istr -> {
                     String ret;
                     ret = istr.readString();
                     return ret;
                 });
        return f;
    }

    default fileInfo[] searchByAuthor(String author)
    {
        return searchByAuthor(author, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default fileInfo[] searchByAuthor(String author, java.util.Map<String, String> context)
    {
        return _iceI_searchByAuthorAsync(author, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<fileInfo[]> searchByAuthorAsync(String author)
    {
        return _iceI_searchByAuthorAsync(author, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<fileInfo[]> searchByAuthorAsync(String author, java.util.Map<String, String> context)
    {
        return _iceI_searchByAuthorAsync(author, context, false);
    }

    default com.zeroc.IceInternal.OutgoingAsync<fileInfo[]> _iceI_searchByAuthorAsync(String iceP_author, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<fileInfo[]> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "searchByAuthor", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_author);
                 }, istr -> {
                     fileInfo[] ret;
                     ret = fileInfosHelper.read(istr);
                     istr.readPendingValues();
                     return ret;
                 });
        return f;
    }

    default fileInfo[] searchByName(String name)
    {
        return searchByName(name, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default fileInfo[] searchByName(String name, java.util.Map<String, String> context)
    {
        return _iceI_searchByNameAsync(name, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<fileInfo[]> searchByNameAsync(String name)
    {
        return _iceI_searchByNameAsync(name, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<fileInfo[]> searchByNameAsync(String name, java.util.Map<String, String> context)
    {
        return _iceI_searchByNameAsync(name, context, false);
    }

    default com.zeroc.IceInternal.OutgoingAsync<fileInfo[]> _iceI_searchByNameAsync(String iceP_name, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<fileInfo[]> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "searchByName", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_name);
                 }, istr -> {
                     fileInfo[] ret;
                     ret = fileInfosHelper.read(istr);
                     istr.readPendingValues();
                     return ret;
                 });
        return f;
    }

    default fileInfo[] searchByGenre(String genre)
    {
        return searchByGenre(genre, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default fileInfo[] searchByGenre(String genre, java.util.Map<String, String> context)
    {
        return _iceI_searchByGenreAsync(genre, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<fileInfo[]> searchByGenreAsync(String genre)
    {
        return _iceI_searchByGenreAsync(genre, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<fileInfo[]> searchByGenreAsync(String genre, java.util.Map<String, String> context)
    {
        return _iceI_searchByGenreAsync(genre, context, false);
    }

    default com.zeroc.IceInternal.OutgoingAsync<fileInfo[]> _iceI_searchByGenreAsync(String iceP_genre, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<fileInfo[]> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "searchByGenre", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_genre);
                 }, istr -> {
                     fileInfo[] ret;
                     ret = fileInfosHelper.read(istr);
                     istr.readPendingValues();
                     return ret;
                 });
        return f;
    }

    default fileInfo[] searchByYear(String year)
    {
        return searchByYear(year, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default fileInfo[] searchByYear(String year, java.util.Map<String, String> context)
    {
        return _iceI_searchByYearAsync(year, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<fileInfo[]> searchByYearAsync(String year)
    {
        return _iceI_searchByYearAsync(year, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<fileInfo[]> searchByYearAsync(String year, java.util.Map<String, String> context)
    {
        return _iceI_searchByYearAsync(year, context, false);
    }

    default com.zeroc.IceInternal.OutgoingAsync<fileInfo[]> _iceI_searchByYearAsync(String iceP_year, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<fileInfo[]> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "searchByYear", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_year);
                 }, istr -> {
                     fileInfo[] ret;
                     ret = fileInfosHelper.read(istr);
                     istr.readPendingValues();
                     return ret;
                 });
        return f;
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static ManageMusicPrx checkedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, ice_staticId(), ManageMusicPrx.class, _ManageMusicPrxI.class);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static ManageMusicPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, context, ice_staticId(), ManageMusicPrx.class, _ManageMusicPrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static ManageMusicPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, ice_staticId(), ManageMusicPrx.class, _ManageMusicPrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static ManageMusicPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, context, ice_staticId(), ManageMusicPrx.class, _ManageMusicPrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @return A proxy for this type.
     **/
    static ManageMusicPrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, ManageMusicPrx.class, _ManageMusicPrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type.
     **/
    static ManageMusicPrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, facet, ManageMusicPrx.class, _ManageMusicPrxI.class);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the per-proxy context.
     * @param newContext The context for the new proxy.
     * @return A proxy with the specified per-proxy context.
     **/
    @Override
    default ManageMusicPrx ice_context(java.util.Map<String, String> newContext)
    {
        return (ManageMusicPrx)_ice_context(newContext);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the adapter ID.
     * @param newAdapterId The adapter ID for the new proxy.
     * @return A proxy with the specified adapter ID.
     **/
    @Override
    default ManageMusicPrx ice_adapterId(String newAdapterId)
    {
        return (ManageMusicPrx)_ice_adapterId(newAdapterId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoints.
     * @param newEndpoints The endpoints for the new proxy.
     * @return A proxy with the specified endpoints.
     **/
    @Override
    default ManageMusicPrx ice_endpoints(com.zeroc.Ice.Endpoint[] newEndpoints)
    {
        return (ManageMusicPrx)_ice_endpoints(newEndpoints);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator cache timeout.
     * @param newTimeout The new locator cache timeout (in seconds).
     * @return A proxy with the specified locator cache timeout.
     **/
    @Override
    default ManageMusicPrx ice_locatorCacheTimeout(int newTimeout)
    {
        return (ManageMusicPrx)_ice_locatorCacheTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the invocation timeout.
     * @param newTimeout The new invocation timeout (in seconds).
     * @return A proxy with the specified invocation timeout.
     **/
    @Override
    default ManageMusicPrx ice_invocationTimeout(int newTimeout)
    {
        return (ManageMusicPrx)_ice_invocationTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for connection caching.
     * @param newCache <code>true</code> if the new proxy should cache connections; <code>false</code> otherwise.
     * @return A proxy with the specified caching policy.
     **/
    @Override
    default ManageMusicPrx ice_connectionCached(boolean newCache)
    {
        return (ManageMusicPrx)_ice_connectionCached(newCache);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoint selection policy.
     * @param newType The new endpoint selection policy.
     * @return A proxy with the specified endpoint selection policy.
     **/
    @Override
    default ManageMusicPrx ice_endpointSelection(com.zeroc.Ice.EndpointSelectionType newType)
    {
        return (ManageMusicPrx)_ice_endpointSelection(newType);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for how it selects endpoints.
     * @param b If <code>b</code> is <code>true</code>, only endpoints that use a secure transport are
     * used by the new proxy. If <code>b</code> is false, the returned proxy uses both secure and
     * insecure endpoints.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default ManageMusicPrx ice_secure(boolean b)
    {
        return (ManageMusicPrx)_ice_secure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the encoding used to marshal parameters.
     * @param e The encoding version to use to marshal request parameters.
     * @return A proxy with the specified encoding version.
     **/
    @Override
    default ManageMusicPrx ice_encodingVersion(com.zeroc.Ice.EncodingVersion e)
    {
        return (ManageMusicPrx)_ice_encodingVersion(e);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its endpoint selection policy.
     * @param b If <code>b</code> is <code>true</code>, the new proxy will use secure endpoints for invocations
     * and only use insecure endpoints if an invocation cannot be made via secure endpoints. If <code>b</code> is
     * <code>false</code>, the proxy prefers insecure endpoints to secure ones.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default ManageMusicPrx ice_preferSecure(boolean b)
    {
        return (ManageMusicPrx)_ice_preferSecure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the router.
     * @param router The router for the new proxy.
     * @return A proxy with the specified router.
     **/
    @Override
    default ManageMusicPrx ice_router(com.zeroc.Ice.RouterPrx router)
    {
        return (ManageMusicPrx)_ice_router(router);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator.
     * @param locator The locator for the new proxy.
     * @return A proxy with the specified locator.
     **/
    @Override
    default ManageMusicPrx ice_locator(com.zeroc.Ice.LocatorPrx locator)
    {
        return (ManageMusicPrx)_ice_locator(locator);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for collocation optimization.
     * @param b <code>true</code> if the new proxy enables collocation optimization; <code>false</code> otherwise.
     * @return A proxy with the specified collocation optimization.
     **/
    @Override
    default ManageMusicPrx ice_collocationOptimized(boolean b)
    {
        return (ManageMusicPrx)_ice_collocationOptimized(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses twoway invocations.
     * @return A proxy that uses twoway invocations.
     **/
    @Override
    default ManageMusicPrx ice_twoway()
    {
        return (ManageMusicPrx)_ice_twoway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses oneway invocations.
     * @return A proxy that uses oneway invocations.
     **/
    @Override
    default ManageMusicPrx ice_oneway()
    {
        return (ManageMusicPrx)_ice_oneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch oneway invocations.
     * @return A proxy that uses batch oneway invocations.
     **/
    @Override
    default ManageMusicPrx ice_batchOneway()
    {
        return (ManageMusicPrx)_ice_batchOneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses datagram invocations.
     * @return A proxy that uses datagram invocations.
     **/
    @Override
    default ManageMusicPrx ice_datagram()
    {
        return (ManageMusicPrx)_ice_datagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch datagram invocations.
     * @return A proxy that uses batch datagram invocations.
     **/
    @Override
    default ManageMusicPrx ice_batchDatagram()
    {
        return (ManageMusicPrx)_ice_batchDatagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, except for compression.
     * @param co <code>true</code> enables compression for the new proxy; <code>false</code> disables compression.
     * @return A proxy with the specified compression setting.
     **/
    @Override
    default ManageMusicPrx ice_compress(boolean co)
    {
        return (ManageMusicPrx)_ice_compress(co);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection timeout setting.
     * @param t The connection timeout for the proxy in milliseconds.
     * @return A proxy with the specified timeout.
     **/
    @Override
    default ManageMusicPrx ice_timeout(int t)
    {
        return (ManageMusicPrx)_ice_timeout(t);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection ID.
     * @param connectionId The connection ID for the new proxy. An empty string removes the connection ID.
     * @return A proxy with the specified connection ID.
     **/
    @Override
    default ManageMusicPrx ice_connectionId(String connectionId)
    {
        return (ManageMusicPrx)_ice_connectionId(connectionId);
    }

    static String ice_staticId()
    {
        return "::MP3::ManageMusic";
    }
}
