# -*- coding: utf-8 -*-
# **********************************************************************
#
# Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
#
# This copy of Ice is licensed to you under the terms described in the
# ICE_LICENSE file included in this distribution.
#
# **********************************************************************
#
# Ice version 3.7.0
#
# <auto-generated>
#
# Generated from file `MP3IceInterface.ice'
#
# Warning: do not edit this file.
#
# </auto-generated>
#

from sys import version_info as _version_info_
import Ice, IcePy

# Start of module MP3
_M_MP3 = Ice.openModule('MP3')
__name__ = 'MP3'

if '_t_listMusiques' not in _M_MP3.__dict__:
    _M_MP3._t_listMusiques = IcePy.defineSequence('::MP3::listMusiques', (), IcePy._t_string)

_M_MP3._t_ManageMusic = IcePy.defineValue('::MP3::ManageMusic', Ice.Value, -1, (), False, True, None, ())

if 'ManageMusicPrx' not in _M_MP3.__dict__:
    _M_MP3.ManageMusicPrx = Ice.createTempClass()
    class ManageMusicPrx(Ice.ObjectPrx):

        def getListeMusic(self, context=None):
            return _M_MP3.ManageMusic._op_getListeMusic.invoke(self, ((), context))

        def getListeMusicAsync(self, context=None):
            return _M_MP3.ManageMusic._op_getListeMusic.invokeAsync(self, ((), context))

        def begin_getListeMusic(self, _response=None, _ex=None, _sent=None, context=None):
            return _M_MP3.ManageMusic._op_getListeMusic.begin(self, ((), _response, _ex, _sent, context))

        def end_getListeMusic(self, _r):
            return _M_MP3.ManageMusic._op_getListeMusic.end(self, _r)

        def streamerMusique(self, mediaName, ipClient, context=None):
            return _M_MP3.ManageMusic._op_streamerMusique.invoke(self, ((mediaName, ipClient), context))

        def streamerMusiqueAsync(self, mediaName, ipClient, context=None):
            return _M_MP3.ManageMusic._op_streamerMusique.invokeAsync(self, ((mediaName, ipClient), context))

        def begin_streamerMusique(self, mediaName, ipClient, _response=None, _ex=None, _sent=None, context=None):
            return _M_MP3.ManageMusic._op_streamerMusique.begin(self, ((mediaName, ipClient), _response, _ex, _sent, context))

        def end_streamerMusique(self, _r):
            return _M_MP3.ManageMusic._op_streamerMusique.end(self, _r)

        def stopMusique(self, ipClient, context=None):
            return _M_MP3.ManageMusic._op_stopMusique.invoke(self, ((ipClient, ), context))

        def stopMusiqueAsync(self, ipClient, context=None):
            return _M_MP3.ManageMusic._op_stopMusique.invokeAsync(self, ((ipClient, ), context))

        def begin_stopMusique(self, ipClient, _response=None, _ex=None, _sent=None, context=None):
            return _M_MP3.ManageMusic._op_stopMusique.begin(self, ((ipClient, ), _response, _ex, _sent, context))

        def end_stopMusique(self, _r):
            return _M_MP3.ManageMusic._op_stopMusique.end(self, _r)

        @staticmethod
        def checkedCast(proxy, facetOrContext=None, context=None):
            return _M_MP3.ManageMusicPrx.ice_checkedCast(proxy, '::MP3::ManageMusic', facetOrContext, context)

        @staticmethod
        def uncheckedCast(proxy, facet=None):
            return _M_MP3.ManageMusicPrx.ice_uncheckedCast(proxy, facet)

        @staticmethod
        def ice_staticId():
            return '::MP3::ManageMusic'
    _M_MP3._t_ManageMusicPrx = IcePy.defineProxy('::MP3::ManageMusic', ManageMusicPrx)

    _M_MP3.ManageMusicPrx = ManageMusicPrx
    del ManageMusicPrx

    _M_MP3.ManageMusic = Ice.createTempClass()
    class ManageMusic(Ice.Object):

        def ice_ids(self, current=None):
            return ('::Ice::Object', '::MP3::ManageMusic')

        def ice_id(self, current=None):
            return '::MP3::ManageMusic'

        @staticmethod
        def ice_staticId():
            return '::MP3::ManageMusic'

        def getListeMusic(self, current=None):
            raise NotImplementedError("servant method 'getListeMusic' not implemented")

        def streamerMusique(self, mediaName, ipClient, current=None):
            raise NotImplementedError("servant method 'streamerMusique' not implemented")

        def stopMusique(self, ipClient, current=None):
            raise NotImplementedError("servant method 'stopMusique' not implemented")

        def __str__(self):
            return IcePy.stringify(self, _M_MP3._t_ManageMusicDisp)

        __repr__ = __str__

    _M_MP3._t_ManageMusicDisp = IcePy.defineClass('::MP3::ManageMusic', ManageMusic, (), None, ())
    ManageMusic._ice_type = _M_MP3._t_ManageMusicDisp

    ManageMusic._op_getListeMusic = IcePy.Operation('getListeMusic', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (), (), ((), _M_MP3._t_listMusiques, False, 0), ())
    ManageMusic._op_streamerMusique = IcePy.Operation('streamerMusique', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), IcePy._t_string, False, 0), ((), IcePy._t_string, False, 0)), (), ((), IcePy._t_bool, False, 0), ())
    ManageMusic._op_stopMusique = IcePy.Operation('stopMusique', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), IcePy._t_string, False, 0),), (), ((), IcePy._t_bool, False, 0), ())

    _M_MP3.ManageMusic = ManageMusic
    del ManageMusic

# End of module MP3
